package vista;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import Modelo.*;
import ModeloDAO.*;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author ediso
 */
public class InterUsuario extends javax.swing.JInternalFrame {
    
    public InterUsuario() {
        initComponents();
        
        this.CargarRol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usr_name = new javax.swing.JTextField();
        cbo_cargo = new javax.swing.JComboBox<>();
        btn_Regresar = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        txt_usr_pass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_usr_nom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_usr_ape = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_usr_telf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_usr_name.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        txt_usr_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_usr_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usr_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usr_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 230, 30));

        cbo_cargo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        cbo_cargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(cbo_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, 30));

        btn_Regresar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        btn_Regresar.setText("Regresar al login");
        btn_Regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 198, 89), new java.awt.Color(255, 198, 89), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_Regresar.setContentAreaFilled(false);
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 130, 30));

        btn_registrar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 198, 89), new java.awt.Color(255, 198, 89), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_registrar.setContentAreaFilled(false);
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 130, 30));

        txt_usr_pass.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        txt_usr_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_usr_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usr_passActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usr_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 230, 30));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel4.setText("Rol:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel6.setText("Nombre de Usuario:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel8.setText("Nombres:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        txt_usr_nom.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        txt_usr_nom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_usr_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usr_nomActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usr_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 230, 30));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel9.setText("Apellidos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        txt_usr_ape.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        txt_usr_ape.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_usr_ape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usr_apeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usr_ape, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 230, 30));

        jLabel2.setText("Telefono:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        txt_usr_telf.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        txt_usr_telf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_usr_telf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usr_telfActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usr_telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 230, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 410));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel10.setText("Teléfono:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usr_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usr_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usr_nameActionPerformed

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
        LoginInternal log = new LoginInternal();
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
       if (txt_usr_nom.getText().isEmpty() || txt_usr_ape.getText().isEmpty() || txt_usr_name.getText().isEmpty()
                || txt_usr_pass.getText().isEmpty() || txt_usr_telf.getText().isEmpty() || cbo_cargo.getSelectedItem().equals(null)) {
            
                   JOptionPane.showMessageDialog(null, "Completa todos los campos");
        } else {
            //validamos si el usuaro ya esta registrado
            Usuario usuario = new Usuario();
            UsuarioDAO usuariodao = new UsuarioDAO();
            if (!usuariodao.existeUsuario(txt_usr_name.getText().trim())) {
                //enviamos datos del usuario
                usuario.setUsr_name(txt_usr_name.getText().trim());
                usuario.setUsr_pass(txt_usr_pass.getText().trim());
                usuario.setUsr_nom(txt_usr_nom.getText().trim());
                usuario.setUsr_ape(txt_usr_ape.getText().trim());
                usuario.setUsr_telf(txt_usr_telf.getText().trim());
                usuario.setUsr_status(1);
                // Hacer algo con el índice seleccionado
                switch (cbo_cargo.getSelectedIndex()) {
                    case 1:
                        // Acciones relacionadas con car_cod 1
                        usuario.setCar_cod(1);
                        break;
                    case 2:
                        // Acciones relacionadas con car_cod 2
                        usuario.setCar_cod(2);
                        break;
                    case 3:
                        // Acciones relacionadas con car_cod 3
                        usuario.setCar_cod(2);
                        break;
                    default:
                        // Manejar otros casos si es necesario
                        break;
                }
                
                
                if (usuariodao.guardarUsuario(usuario)) {
                    JOptionPane.showMessageDialog(null, "¡Usuario Registrado!");
                } else {
                    JOptionPane.showMessageDialog(null, "¡Error al registrar Usuario!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El Usuario ya esta registrado, ingrese otro.");
            }
        }
        this.Limpiar();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_usr_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usr_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usr_passActionPerformed

    private void txt_usr_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usr_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usr_nomActionPerformed

    private void txt_usr_apeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usr_apeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usr_apeActionPerformed

    private void txt_usr_telfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usr_telfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usr_telfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Regresar;
    public javax.swing.JButton btn_registrar;
    public javax.swing.JComboBox<String> cbo_cargo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_usr_ape;
    public javax.swing.JTextField txt_usr_name;
    public javax.swing.JTextField txt_usr_nom;
    public javax.swing.JTextField txt_usr_pass;
    public javax.swing.JTextField txt_usr_telf;
    // End of variables declaration//GEN-END:variables
     /**
     *
     * Metodo para limpiar campos
     */
    private void Limpiar() {
        txt_usr_name.setText("");
        txt_usr_pass.setText("");
        txt_usr_nom.setText("");
        txt_usr_ape.setText("");
        txt_usr_telf.setText("");
        cbo_cargo.setSelectedIndex(0);
    }

  
        /**
     *
     * Metodo para cargar las categorias
     */
    private void CargarRol() {
        Connection cn = ConexionSQL.Conectar.getConexion();
        String sql = "select * from cargo";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cbo_cargo.removeAllItems();
            cbo_cargo.addItem("Seleccione Cargo:");
            while (rs.next()) {
                cbo_cargo.addItem(rs.getString("car_nom"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias");
        }
    }
    
}
