package vista;

//import controlador.Ctrl_Usuario;
import ConexionSQL.Conectar;
import Modelo.Ingrediente;
import Modelo.Producto;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import Modelo.Usuario;
import ModeloDAO.IngredienteDAO;
import ModeloDAO.ProductoDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class InterIngredientes extends javax.swing.JInternalFrame {

    public InterIngredientes() {
        initComponents();

        this.setTitle("Registro de ingredientes");
        this.CargarComboInsumos();
        this.CargarComboProductos();
        this.CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboinsumo = new javax.swing.JComboBox<>();
        txt_cantidad = new javax.swing.JTextField();
        comboproducto = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaIngredientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 198, 89));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRAR CANTIDADES ");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 30));

        jPanel2.setBackground(new java.awt.Color(252, 248, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, null, null));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 140, 30));

        btnAtras.setBackground(new java.awt.Color(255, 255, 255));
        btnAtras.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras.setText("Atrás");
        btnAtras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, null, null));
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 170, 30));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Insumo:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Producto:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 30));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cantidad:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 80, -1));

        comboinsumo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        comboinsumo.setForeground(new java.awt.Color(0, 0, 0));
        comboinsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ingrediente" }));
        comboinsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboinsumoActionPerformed(evt);
            }
        });
        jPanel2.add(comboinsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 170, 30));

        txt_cantidad.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jPanel2.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 100, 30));

        comboproducto.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        comboproducto.setForeground(new java.awt.Color(0, 0, 0));
        comboproducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione producto" }));
        comboproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboproductoActionPerformed(evt);
            }
        });
        jPanel2.add(comboproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaIngredientes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 7, 610, 170));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 630, 190));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String producto = comboproducto.getSelectedItem().toString().trim();
        String insumos = comboinsumo.getSelectedItem().toString().trim();

        if (txt_cantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad");
        } else {
            if (producto.equalsIgnoreCase("Seleccione producto:")) {
                JOptionPane.showMessageDialog(null, "Seleccione producto");
            } else {
                if (insumos.equalsIgnoreCase("Seleccione Insumo:")) {
                    JOptionPane.showMessageDialog(null, "Seleccione insumo");
                } else {
                    Ingrediente ingrediente = new Ingrediente();
                    IngredienteDAO ingredientedao = new IngredienteDAO();
                    int idinsumo = ingredientedao.buscaridinsumo(comboinsumo.getSelectedItem().toString());
                    int idproducto = ingredientedao.buscaridproducto(comboproducto.getSelectedItem().toString());
                    
                    ingrediente.setCantidad(Integer.parseInt(txt_cantidad.getText()));
                    ingrediente.setIdInsumo(idinsumo);
                    ingrediente.setIdProducto(idproducto);
                    System.out.println("id producto" + idproducto);
                    System.out.println("id insumo" + idinsumo);

                    if (ingredientedao.guardar(ingrediente)) {
                        JOptionPane.showMessageDialog(null, "¡Datos del ingrediente actualizados!");
                        this.CargarTabla();
                        this.Limpiar();
                    } else {
                        JOptionPane.showMessageDialog(null, "¡Error al guardar!");
                    }
                }
            }
        }

        this.Limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void comboinsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboinsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboinsumoActionPerformed

    private void comboproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboproductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaIngredientes;
    private javax.swing.JButton btnAtras;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox<String> comboinsumo;
    public javax.swing.JComboBox<String> comboproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txt_cantidad;
    // End of variables declaration//GEN-END:variables
     /**
     *
     * Metodo para limpiar campos
     */
    private void Limpiar() {
        txt_cantidad.setText("");
    }

    private void CargarTabla() {
        DefaultTableModel model = new DefaultTableModel();

        InterIngredientes.TablaIngredientes = new JTable(model);
        this.jScrollPane1.setViewportView(InterIngredientes.TablaIngredientes);

        model.addColumn("PRODUCTO°");//ID
        model.addColumn("INSUMO");
        model.addColumn("CANTIDAD DE INSUMO");

        Object[] fila = new Object[3];
        IngredienteDAO ingredientedao = new IngredienteDAO();
        List<Ingrediente> lista = ingredientedao.lista();

        for (Ingrediente x : lista) {
            fila[0] = x.getNombreproducto();
            fila[1] = x.getNombreinsumo();
            fila[2] = x.getCantidad();
            model.addRow(fila);
        }
    }

    private void CargarComboProductos() {

        Connection cn = Conectar.getConexion();
        String sql = "select * from PRODUCTO";
        Statement st;
        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            comboproducto.removeAllItems();
            comboproducto.addItem("Seleccione producto:");
            while (rs.next()) {
                comboproducto.addItem(rs.getString("prod_nom"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar los productos en: " + e);
        }

    }

    private void CargarComboInsumos() {

        Connection cn = Conectar.getConexion();
        String sql = "select * from Insumos";
        Statement st;
        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            comboinsumo.removeAllItems();
            comboinsumo.addItem("Seleccione Insumo:");
            while (rs.next()) {
                comboinsumo.addItem(rs.getString("ins_nom"));
            }

        } catch (SQLException e) {
            System.out.println("Error al cargar los productos en: " + e);
        }

    }

}
