package vista;


import ConexionSQL.Conectar;
import Modelo.*;
import ModeloDAO.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ediso
 */
public class InterGestionarProveedor extends javax.swing.JInternalFrame {

    private int idTecnico;

    public InterGestionarProveedor() {
        initComponents();

        this.setTitle("Gestionar Proveedores");
        //Cargar tabla
        this.CargarTablaTecnicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_proveedor = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        txt_ruc = new javax.swing.JTextField();
        jButton_actualizar1 = new javax.swing.JButton();
        jButton_eliminar1 = new javax.swing.JButton();
        btnAtras1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 198, 89));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MENÚ - GESTIONAR PROVEEDOR");
        jPanel5.add(jLabel4);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 30));

        jPanel6.setBackground(new java.awt.Color(252, 248, 232));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_proveedor.setForeground(new java.awt.Color(0, 102, 102));
        jTable_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_proveedor);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 200));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 680, 220));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nombre:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 80, -1));

        txt_nombre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 240, -1));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("RUC:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 70, -1));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Descripcion");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 80, -1));

        txt_descripcion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        txt_descripcion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 240, -1));

        txt_ruc.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        txt_ruc.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(txt_ruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 240, -1));

        jButton_actualizar1.setBackground(new java.awt.Color(252, 248, 232));
        jButton_actualizar1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jButton_actualizar1.setForeground(new java.awt.Color(0, 0, 0));
        jButton_actualizar1.setText("GUARDAR");
        jButton_actualizar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, null, null));
        jButton_actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton_actualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 200, 30));

        jButton_eliminar1.setBackground(new java.awt.Color(252, 248, 232));
        jButton_eliminar1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        jButton_eliminar1.setForeground(new java.awt.Color(0, 0, 0));
        jButton_eliminar1.setText("ELIMINAR");
        jButton_eliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, null, null));
        jButton_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminar1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton_eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 200, 30));

        btnAtras1.setBackground(new java.awt.Color(252, 248, 232));
        btnAtras1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        btnAtras1.setForeground(new java.awt.Color(0, 0, 0));
        btnAtras1.setText("ATRÁS");
        btnAtras1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.black, null, null));
        btnAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 200, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed

        ProveedorDAO proveedordao = new ProveedorDAO();
        if (idTecnico == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione un tecnico!");
        } else {
            if (!proveedordao.eliminar(idTecnico)) {
                JOptionPane.showMessageDialog(null, "¡Cliente Eliminado!");
                this.CargarTablaTecnicos();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al eliminar técnico!");
                this.Limpiar();
            }
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void jButton_actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar1ActionPerformed

        if (txt_nombre.getText().isEmpty() && txt_descripcion.getText().isEmpty()
                && txt_ruc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Completa todos los campos!");
        } else {

            Proveedor proveedor = new Proveedor();
            ProveedorDAO proveedordao = new ProveedorDAO();

            proveedor.setNombre(txt_nombre.getText().trim());
            proveedor.setDescripcion(txt_descripcion.getText().trim());
            proveedor.setRuc(Integer.parseInt(txt_ruc.getText().trim()));

            if (proveedordao.actualizar(proveedor, idTecnico)) {
                JOptionPane.showMessageDialog(null, "¡Datos del proveedor actualizados!");
                this.CargarTablaTecnicos();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al actualizar!");
            }

        }
    }//GEN-LAST:event_jButton_actualizar1ActionPerformed

    private void jButton_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminar1ActionPerformed

        ProveedorDAO proveedordao = new ProveedorDAO();
        if (idTecnico == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione un proveedor!");
        } else {
            if (!proveedordao.eliminar(idTecnico)) {
                JOptionPane.showMessageDialog(null, "¡Proveedor Eliminado!");
                this.CargarTablaTecnicos();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al eliminar proveedor!");
                this.Limpiar();
            }
        }
    }//GEN-LAST:event_jButton_eliminar1ActionPerformed

    private void btnAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtras1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras1;
    private javax.swing.JButton jButton_actualizar1;
    private javax.swing.JButton jButton_eliminar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable_proveedor;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_ruc;
    // End of variables declaration//GEN-END:variables

    /*
     * *****************************************************
     * metodo para limpiar
     * *****************************************************
     */
    private void Limpiar() {

    }


    /*
     * *****************************************************
     * metodo para mostrar todos los clientes registrados
     * *****************************************************
     */
    private void CargarTablaTecnicos() {
        DefaultTableModel model = new DefaultTableModel();
        InterGestionarProveedor.jTable_proveedor = new JTable(model);
        InterGestionarProveedor.jScrollPane2.setViewportView(InterGestionarProveedor.jTable_proveedor);
        
        model.addColumn("N°");//ID
        model.addColumn("NOMBRE");
        model.addColumn("DESCRIPCION:");
        model.addColumn("RUC");
        
        Object[] fila = new Object[6];
        ProveedorDAO proveedordao = new ProveedorDAO();
        List<Proveedor> lista = proveedordao.lista();

        for (Proveedor x : lista) {
            fila[0] = x.getIdProveedor();
            fila[1] = x.getNombre();
            fila[2] = x.getDescripcion();
            fila[3] = x.getRuc();
            model.addRow(fila);
        }
        
        
        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_proveedor.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_proveedor.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idTecnico = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosTecnicoSeleccionado(idTecnico);//metodo
                }
            }
        });
    }


    /*
     * **************************************************
     * Metodo que envia datos seleccionados
     * **************************************************
     */
    private void EnviarDatosTecnicoSeleccionado(int idProveedor) {
        try {
            Connection con = Conectar.getConexion();
            PreparedStatement pst = con.prepareStatement(
                    "select * from proveedor where pro_cod= '" + idProveedor + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txt_nombre.setText(rs.getString("pro_nom"));
                txt_descripcion.setText(rs.getString("pro_des"));
                txt_ruc.setText(Integer.toString(rs.getInt("pro_ruc")));

            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar proveedor: " + e);
        }
    }

}
