/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import ConexionSQL.Conectar;
import ModeloDAO.*;
import javax.swing.JOptionPane;
import Modelo.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author kevfe
 */
public class LoginInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginInternal
     */
    public LoginInternal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_error_usr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 359));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 198, 89));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 146, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 198, 89));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 226, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 276, 190, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 196, 190, 20));

        txt_usuario.setBorder(null);
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 166, 150, 30));

        txt_password.setBorder(null);
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 246, 150, 30));

        btnEntrar.setBackground(new java.awt.Color(255, 153, 51));
        btnEntrar.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 12)); // NOI18N
        btnEntrar.setText("Iniciar Sesión");
        btnEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 316, 130, 30));

        jButton2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        jButton2.setText("Registrarse");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 356, 130, 10));

        lbl_error_usr.setBackground(new java.awt.Color(255, 255, 255));
        lbl_error_usr.setForeground(new java.awt.Color(255, 255, 255));
        lbl_error_usr.setText("jLabel4");
        jPanel1.add(lbl_error_usr, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 16, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        login();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InterUsuario reg = new InterUsuario();
        this.dispose();
        reg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
private void login() {
    if (!txt_usuario.getText().isEmpty() && txt_password.getPassword().length > 0) {
        UsuarioDAO usuariodao = new UsuarioDAO();
        Usuario usuario = new Usuario();
        usuario.setUsr_name(txt_usuario.getText().trim());
        usuario.setUsr_pass(new String(txt_password.getPassword()));

        if (usuariodao.loginUser(usuario)) {
            int estado = 1;
            int cargo = obtenerCarCod(txt_usuario.getText());
            
            if (usuarioValido(usuario)) {
                switch (cargo) {
                    case 1:
                        switch (estado) {
                            case 1:
                               
                                configurarMenu(false, true, true, true, true, true, true, true, true);
                                break;
                            case 0:
                                lbl_error_usr.setText("El Administrador se encuentra inactivo");
                                break;
                        }
                        break;
                    case 2:
                        switch (estado) {
                            case 1:
                               configurarMenu(false, false, false, true, true, false, true, true, true);
                                break;
                            case 2:
                                lbl_error_usr.setText("El Vendedor se encuentra inactivo");
                                break;
                        }
                        break;
                    case 3:
                        switch (estado) {
                            case 1:
                                 configurarMenu(false, false, false, false, true, false, false, true, true);
                                break;
                            case 2:
                                lbl_error_usr.setText("El Encargado se encuentra inactivo");
                                break;
                        }
                        break;
                }
            } else {
                lbl_error_usr.setText("Usuario no válido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o Clave Incorrectos");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Ingrese sus credenciales");
    }
}

private boolean usuarioValido(Usuario usuario) {
    return usuario != null && usuario.getUsr_name() != null && !usuario.getUsr_name().isEmpty();
}

private int obtenerCarCod(String usr_name) {
    try (Connection con = Conectar.getConexion();
         PreparedStatement pst = con.prepareStatement("SELECT car_cod FROM USUARIO WHERE usr_name = ?")) {

        pst.setString(1, usr_name);

        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("car_cod");
            } else {
                return -1; // Puedes devolver -1 para indicar que el usuario no fue encontrado
            }
        }
    } catch (SQLException e) {
        System.out.println("Error al seleccionar usuario: " + e);
        return -1; // Puedes devolver -1 para indicar un error en la base de datos
    }
}


private void configurarMenu(boolean login, boolean usuarios, boolean proveedores, boolean clientes, boolean productos,
                            boolean categorias, boolean facturar, boolean reportes, boolean historial) {
    FrmMenu.Menu_IniciarSesion.setEnabled(login);
    FrmMenu.Menu_Usuarios.setEnabled(usuarios);
    FrmMenu.Menu_Proveedores.setEnabled(proveedores);
    FrmMenu.Menu_Clientes.setEnabled(clientes);
    FrmMenu.Menu_Productos.setEnabled(productos);
    FrmMenu.Menu_Categorias.setEnabled(categorias);
    FrmMenu.Menu_Facturar.setEnabled(facturar);
    FrmMenu.Menu_Reportes.setEnabled(reportes);
    FrmMenu.Menu_Historial.setEnabled(historial);
    FrmMenu.Menu_CerrarSesion.setEnabled(true);
    dispose();
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEntrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_error_usr;
    public javax.swing.JPasswordField txt_password;
    public javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
